### ISSUE TITLE
NullReferenceException when using Parser.Default

### ISSUE THREAD

**Issue by r-moeritz** [gsscoder/commandline#102]
If I new up a `Parser` instance & call `ParseArguments` or `ParseArgumentsStrict` all is well, but calling either of these methods on `Parser.Default` raises a `NullReferenceException`. Exception details below:

```
System.NullReferenceException was unhandled
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=CommandLine
  StackTrace:
       at CommandLine.HelpVerbOptionAttribute.InvokeMethod(Object target, Pair`2 helpInfo, String verb, String& text)
       at CommandLine.Parser.DisplayHelpVerbText(Object options, Pair`2 helpInfo, String verb)
       at CommandLine.Parser.DoParseArgumentsVerbs(String[] args, Object options, Object& verbInstance)
       at CommandLine.Parser.ParseArgumentsStrict(String[] args, Object options, Action`2 onVerbCommand, Action onFail)
       at EnableDisableDevice.Program.Main(String[] args) in c:\Users\ralphm\Temp\src\EnableDisableDevice\EnableDisableDevice\Program.cs:line 16
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

```

**Comment by gsscoder** [comment]
@turbanoff, this was (because we're talking of 1.9.* stable) I design time problem, anyway a better `InvalidOperation(...)` would have been better.

Please switch to **2.0.x**: no need to define anything more than options in your parsing target + other goodies.

https://github.com/gsscoder/commandline/wiki/Latest-Version
