### ISSUE TITLE
System.ObjectDisposedException thrown

### ISSUE THREAD

**Issue by digitalbricklayer** [gsscoder/commandline#105]
I am running CommandLineParser version 1.9.71 installed from nuget.

When my test passed an empty args array through to the parser code to make sure that the help text is displayed, CommandLineParser throws a System.ObjectDisposedException exception with the message "Cannot write to a closed TextWriter."

There is a gist here showing the parser code + parser object: https://gist.github.com/digitalbricklayer/7103320

The full stack trace is here:

Test method Xsensior.Lite.Database.Cli.Tests.Unit.LiteDatabaseRunnerTests.Run_With_No_Arguments_Returns_Invalid_Args threw exception: 
 System.ObjectDisposedException: Cannot write to a closed TextWriter.
     at System.IO.__Error.WriterClosed()
    at System.IO.StringWriter.Write(String value)
    at Microsoft.VisualStudio.TestTools.TestTypes.Unit.ThreadSafeStringWriter.Write(String value)
    at System.IO.TextWriter.SyncTextWriter.Write(String value)
    at CommandLine.Parser.DisplayHelpVerbText(Object options, Pair`2 helpInfo, String verb)
    at CommandLine.Parser.DoParseArgumentsVerbs(String[] args, Object options, Object& verbInstance)
    at CommandLine.Parser.ParseArguments(String[] args, Object options, Action`2 onVerbCommand)
    at Xsensior.Lite.Database.Cli.LiteDatabaseRunner.Run(String[] args) in c:\BuildAgent\work\30b1ceed2db94149\Xsensior.Lite.Model.Library.Database.Tool\LiteDatabaseRunner.cs:line 51
    at Xsensior.Lite.Database.Cli.Tests.Unit.LiteDatabaseRunnerTests.Run_With_No_Arguments_Returns_Invalid_Args() in c:\BuildAgent\work\30b1ceed2db94149\Xsensior.Lite.Database.Cli.Tests.Unit\LiteDatabaseRunnerTests.cs:line 31

**Comment by gsscoder** [comment]
Please switch to 2.0.
Thanks.
