### ISSUE TITLE
IndexOutOfRangeException on parse from multiple threads

### ISSUE THREAD

**Issue by turbanoff** [gsscoder/commandline#139]
It's strange and happens only once. Rerun was not reproduced: maybe data race?
I launched parsing from multiple threads and got a lot of exceptions:
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at CommandLine.Infrastructure.ReflectionCache.set_Item(Pair`2 key, Object value)
   at CommandLine.Infrastructure.ReflectionHelper.RetrievePropertyList[TAttribute](Object target)
   at CommandLine.Parsing.ValueMapper.InitializeValueOption()
   at CommandLine.Parsing.ValueMapper..ctor(Object target, CultureInfo parsingCulture)
   at CommandLine.Parser.DoParseArgumentsCore(String[] args, Object options)
   at CommandLine.Parser.DoParseArgumentsVerbs(String[] args, Object options, Object& verbInstance)
   at CommandLine.Parser.ParseArguments(String[] args, Object options, Action`2 onVerbCommand)
   at OracleScheme.Program.Main(String[] args) in d:\Projects\OracleScheme\OracleScheme\OracleScheme\Program.cs:line 20
```

version - 1.9.71.2

**Comment by gsscoder** [comment]
@turbanoff, so @nemec helped right? I close the issue, but if not feel free to comment...
