### ISSUE TITLE
single dash throws exception

### ISSUE THREAD

**Issue by davhdavh** [gsscoder/commandline#252]
CommandLine.Parser.Default.ParseArguments<object>(new []{"-"});
-> Exception

**Comment by gsscoder** [comment]
This is for 2.0.*? I was about to discovering it with FsCheck but ordinary job distracted me thank you, @davhdavh.

For the moment I can't proceed, please read this temp announcement #250.

Have nice day! :)

**Comment by davhdavh** [comment]
Latest on nuget, so 2.0.257+.
Np on delay for fixing, a few weeks wont make any difference for me.

On Wed, Oct 7, 2015 at 1:22 PM, Giacomo Stelluti Scala <
notifications@github.com> wrote:

> This is for 2.0.*? I was about to discovering it with FsCheck but ordinary
> job distracted me thank you, @davhdavh <https://github.com/davhdavh>.
>
> For the moment I can't proceed, please read this temp announcement #250
> <https://github.com/gsscoder/commandline/issues/250>.
>
> Have nice day! :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gsscoder/commandline/issues/252#issuecomment-146089326>
> .
>



-- 
Dennis

**Comment by nemec** [comment]
@davhdavh for reference, is this the error message you see?

    System.IndexOutOfRangeException : Index was outside the bounds of the array.
    StackTrace:	
        at System.String.get_Chars(Int32 index)
           at CommandLine.Core.Tokenizer.<TokenizeShortName>d__3e.MoveNext() in c:\commandline\src\CommandLine\Core\Tokenizer.cs:line 141
           at System.Linq.Enumerable.<SelectManyIterator>d__4`3.MoveNext()
           at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
           at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
           at CSharpx.EnumerableExtensions.Memorize[T](IEnumerable`1 source) in c:\commandline\paket-files\gsscoder\CSharpx\src\CSharpx\EnumerableExtensions.cs:line 377
           at CommandLine.Core.Tokenizer.Tokenize(IEnumerable`1 arguments, Func`2 nameLookup, Func`2 normalize) in c:\commandline\src\CommandLine\Core\Tokenizer.cs:line 29
           at CommandLine.Core.Tokenizer.<>c__DisplayClass39.<ConfigureTokenizer>b__31(IEnumerable`1 arguments, IEnumerable`1 optionSpecs) in c:\commandline\src\CommandLine\Core\Tokenizer.cs:line 122
           at CommandLine.Parser.Tokenize(IEnumerable`1 arguments, IEnumerable`1 optionSpecs, ParserSettings settings) in c:\commandline\src\CommandLine\Parser.cs:line 177
           at CommandLine.Parser.<ParseArguments>b__1[T](IEnumerable`1 arguments, IEnumerable`1 optionSpecs) in c:\commandline\src\CommandLine\Parser.cs:line 97
           at CommandLine.Core.InstanceBuilder.<>c__DisplayClass1e`1.<Build>b__8() in c:\commandline\src\CommandLine\Core\InstanceBuilder.cs:line 45
           at CommandLine.Core.InstanceBuilder.Build[T](Maybe`1 factory, Func`3 tokenizer, IEnumerable`1 arguments, StringComparer nameComparer, CultureInfo parsingCulture, IEnumerable`1 nonFatalErrors) in c:\commandline\src\CommandLine\Core\InstanceBuilder.cs:line 130
           at CommandLine.Parser.ParseArguments[T](IEnumerable`1 args) in c:\commandline\src\CommandLine\Parser.cs:line 94
           at CommandLine.Tests.Unit.ParserTests.Parse_options_with_single_dash() in c:\commandline\tests\CommandLine.Tests\Unit\ParserTests.cs:line 164

**Comment by nemec** [comment]
I think I fixed your issue (see tests in referenced commit), but I'll let you confirm before officially closing this issue. Thanks for reporting it!

**Comment by davhdavh** [comment]
Yes

**Comment by gsscoder** [comment]
Thanks again, @nemec!
