### ISSUE TITLE
[2.0] InvalidOperationException when duplicate option is set on inherited class

### ISSUE THREAD

**Issue by tpluscode** [gsscoder/commandline#266]
I've made a mistake and declared an option with same short name on both base and inherited class. 
Here's the stack trace tip and sample code below

```
Unhandled Exception: System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at CommandLine.Core.TypeLookup.FindTypeDescriptorAndSibling(String name, IEnumerable`1 specifications, StringComparer comparer)
   at CommandLine.Core.InstanceBuilder.<>c__DisplayClass0_0`1.<Build>b__8(String name)
```

```
public abstract class BaseOptions
{
    [Option('d', "devSeeds", HelpText = "Seed database with sample data")]
    public bool IncludeDeveloperSeeds { get; set; }
}

[Verb("local", HelpText = "Updates local database")]
public class LocalOptions : BaseOptions
{
    [Option('d', "database", HelpText = "Database to upgrade")]
    public string DatabaseName { get; set; }
}
```

**Comment by nemec** [comment]
What behavior do you expect to see here? Just a more helpful error message?

**Comment by nemec** [comment]
Got it. I'll make sure the `result.Errors` property contains details about which name is duplicated. Make sure to check there for any errors as the parser will (most likely) no longer throw an exception when you make this mistake.

**Comment by mizipzor** [comment]
@nemec did you ever get around to do this and just forgot to close, or is this still open?

**Comment by nemec** [comment]
No, I haven't had a chance to get to it.
