### ISSUE TITLE
MemberAccessException thrown - Unicode support for names?

### ISSUE THREAD

**Issue by OmegaExtern** [gsscoder/commandline#311]
Running on the latest stable branch ([stable-1.9.71.2](https://github.com/gsscoder/commandline/tree/stable-1.9.71.2)).

```
using System;
using CommandLine;
using CommandLine.Text;

namespace CommandLineTest
{
    internal static class Program
    {
        private static void Main(/*string[] args*/)
        {
            Options options = new Options();

            if (Parser.Default.ParseArguments(new[] { "\u2639", "Hello World" }, options) == false)
            {
                options.GetUsage();
                Console.Read();
                Environment.Exit(Parser.DefaultExitCodeFail);
            }

            Console.Out.WriteLine($"\u2639|ext: {options.TextValue}");
            Console.Out.WriteLine($"n|umeric: {options.NumericValue}");
            Console.Out.WriteLine($"b|ool: {options.BooleanValue.ToString().ToLowerInvariant()}");
            Console.Read();
        }
    }

    internal sealed class Options
    {
        [Option('\u2639', "text", Required = true, HelpText = "Text value here")]
        public string TextValue { get; set; }

        [Option('n', "numeric", HelpText = "Numeric value here")]
        public double NumericValue { get; set; }

        [Option('b', "bool", HelpText = "Boolean true|false value here")]
        public bool BooleanValue { get; set; }

        [HelpOption]
        public void GetUsage() => HelpText.AutoBuild(this, current => HelpText.DefaultParsingErrorsHandler(this, current));
    }
}
```

```
System.MemberAccessException was unhandled
  HResult=-2146233062
  Message=Cannot access member.
  Source=CommandLine
  StackTrace:
       at CommandLine.HelpOptionAttribute.InvokeMethod(Object target, Pair`2 pair, String& text)
       at CommandLine.Parser.DoParseArguments(String[] args, Object options)
       at CommandLineTest.Program.Main() in X:\CommandLineTest\CommandLineTest\Program.cs:line 13
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
```

I have tried embracing the name with a pair of double quotes, like this:
`if (Parser.Default.ParseArguments(new[] { "\"\u2639\"", "Hello World" }, options) == false)`
Still, exception is thrown.

**Comment by OmegaExtern** [comment]
Whoops, it seems like I have forgot to prefix it with "-".
`Parser.Default.ParseArguments(new[] { "-\u2639", "Hello World" }, options)`
Closing this issue.
