### ISSUE TITLE
Help generation crashes when no Author is provided.

### ISSUE THREAD

**Issue by masaeedu** [gsscoder/commandline#332]
I have the following options class:

    class Options
    {
        [Value(0,
            MetaName = "size",
            Required = true,
            HelpText = "Desired size of the target database")]
        public string Size { get; set; }
    }

My `Main` method is set up like so:

```
public static int Main(string[] args)
{
    var result = Parser.Default.ParseArguments<Options>(args);
    return result.MapResult(...);
}
```

When the application is invoked with the arguments `--size "300 GB"`, the following uncaught exception occurs in ParseArguments (the first statement in `Main`):

```
Unhandled Exception: System.ArgumentException: author
   at CommandLine.Text.CopyrightInfo..ctor(Boolean isSymbolUpper, String author, Int32[] copyrightYears)
   at CommandLine.Text.CopyrightInfo.get_Default()
   at CommandLine.Text.HelpText.AutoBuild[T](ParserResult`1 parserResult, Func`2 onError, Func`2 onExample, Boolean verbsIndex)
   at CommandLine.Text.HelpText.AutoBuild[T](ParserResult`1 parserResult)
   at CommandLine.Parser.<>c__DisplayClass17_0`1.<DisplayHelp>b__1(IEnumerable`1 _, TextWriter writer)
   at CSharpx.MaybeExtensions.Do[T1,T2](Maybe`1 maybe, Action`2 action)
   at CommandLine.ParserResultExtensions.WithNotParsed[T](ParserResult`1 result, Action`1 action)
   at CommandLine.Parser.DisplayHelp[T](ParserResult`1 parserResult, TextWriter helpWriter)
   at AgentAutomation.DataFiller.Program.Main(String[] args) in D:\depot\git\AgentAutoUtils\execution\DataFiller\Program.cs:line 24
```

It is totally correct behavior for parsing to fail, since I've configured the `Size` argument as a positional value rather than an option, and so I need to remove the `--size`. 

However, there should be no input that results in an uncaught exception: all errors arising from malformed input should be passed to the error handler lambda. A user entering nonsense should at the very least see the help screen.

**Comment by nemec** [comment]
Have you defined an `AssemblyCopyrightAttribute` or `AssemblyCompanyAttribute` in your application properties and is it non-null/empty? It isn't breaking because of your input but because it's trying to print the help info (including copyright) and there is no author available.

**Comment by masaeedu** [comment]
No, I don't have those. In that case it should probably skip whatever
assembly metadata it was trying to output instead of crashing with an NRE.

**Comment by nemec** [comment]
Yes, that's a really good idea.

**Comment by nemec** [comment]
I've just merged a fix for this. Thank you @anthonylangsworth!

Let me know if there are further issues around missing assembly attributes.
