### ISSUE TITLE
Replace PaserSetting.HelpWriter Throwing exception

### ISSUE THREAD

**Issue by duke605** [gsscoder/commandline#342]
There's a higher than likely chance that this is just me being a derp. But when I try to replace the HelpWriter with null or anything for that matter i get a InvalidOperationException.

The code I'm using.
`Parser.Default.Settings.HelpWriter = null;`

**Comment by nemec** [comment]
Can you post the stack trace? More than likely we fail to do a null check somwhere...

**Comment by duke605** [comment]
I'm more of a java guy when it comes to stack traces so i have no idea if this little bit is what you're looking for

```   at CommandLine.Infrastructure.PopsicleSetter.Set[T](Boolean consumed, T& field, T value)
   at CommandLine.ParserSettings.set_HelpWriter(TextWriter value)
   at WerewolfBot.Program.Main(String[] args) in c:\users\cole\documents\visual studio 2015\Projects\WerewolfBot\WerewolfBot\Program.cs:line 20
```
