### ISSUE TITLE
Please publish new NuGet package. 

### ISSUE THREAD

**Issue by skalinkin** [gsscoder/commandline#363]
Hi Everyone, 
this is a great project, and there is some bug in latest beta version available through NuGet. It was apparently fixed since it is not an issue with latest code. 

Please publish current code to NuGet.

I have: NuGet 2.0.275-beta
symptoms: if Verb has required option, calling for a verb throws OutOfMemmory exception

System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.String.InternalSplitKeepEmptyEntries(Int32[] sepList, Int32[] lengthList, Int32 numReplaces, Int32 count)
   at System.String.SplitInternal(Char[] separator, Int32 count, StringSplitOptions options)
   at CommandLine.Text.HelpText.AddOption(String requiredWord, Int32 maxLength, Specification specification, Int32 widthOfHelpText)
   at CommandLine.Text.HelpText.<>c__DisplayClass62_0.<AddOptionsImpl>b__0(Specification option)
   at CSharpx.EnumerableExtensions.ForEach[T](IEnumerable`1 source, Action`1 action)
   at CommandLine.Text.HelpText.AddOptionsImpl(IEnumerable`1 specifications, String requiredWord, Int32 maximumLength)
   at CommandLine.Text.HelpText.AddOptions[T](ParserResult`1 result)
   at CommandLine.Text.HelpText.AutoBuild[T](ParserResult`1 parserResult, Func`2 onError, Func`2 onExample, Boolean verbsIndex)
   at CommandLine.Text.HelpText.AutoBuild[T](ParserResult`1 parserResult)
   at CommandLine.Parser.<>c__DisplayClass17_0`1.<DisplayHelp>b__1(IEnumerable`1 _, TextWriter writer)
   at CSharpx.MaybeExtensions.Do[T1,T2](Maybe`1 maybe, Action`2 action)
   at CommandLine.Parser.<>c__DisplayClass17_0`1.<DisplayHelp>b__0(IEnumerable`1 errors)
   at CommandLine.ParserResultExtensions.WithNotParsed[T](ParserResult`1 result, Action`1 action)
   at CommandLine.Parser.DisplayHelp[T](ParserResult`1 parserResult, TextWriter helpWriter)
   at CommandLine.Parser.ParseArguments(IEnumerable`1 args, Type[] types)
   at CommandLine.ParserExtensions.ParseArguments[T1,T2,T3,T4,T5,T6](Parser parser, IEnumerable`1 args)

**Comment by nemec** [comment]
Done.
https://www.nuget.org/packages/CommandLineParser/2.1.1-beta
